export interface WMOInterpretation {
  code: number;
  label: string;
  description: string;
  iconDay: string;
  iconNight: string;
  gradientClass: string;
  accentColor: string;
  severity: 'clear' | 'cloudy' | 'rain' | 'snow' | 'storm' | 'fog';
}

export const WMO_Interpretation_Map: Record<number, WMOInterpretation> = {
  0: {
    code: 0,
    label: 'Clear Sky',
    description: 'Completely clear sky with abundant sunshine',
    iconDay: 'Sun',
    iconNight: 'Moon',
    gradientClass: 'from-amber-500/10 via-sky-500/10 to-blue-600/10 border-amber-500/20',
    accentColor: '#f59e0b',
    severity: 'clear',
  },
  1: {
    code: 1,
    label: 'Mainly Clear',
    description: 'Mostly clear skies with a few high clouds',
    iconDay: 'SunMedium',
    iconNight: 'MoonStar',
    gradientClass: 'from-sky-400/10 via-blue-500/10 to-indigo-600/10 border-sky-400/20',
    accentColor: '#38bdf8',
    severity: 'clear',
  },
  2: {
    code: 2,
    label: 'Partly Cloudy',
    description: 'Scattered clouds with periods of sunshine',
    iconDay: 'CloudSun',
    iconNight: 'CloudMoon',
    gradientClass: 'from-sky-500/10 via-slate-400/10 to-slate-600/10 border-sky-300/20',
    accentColor: '#60a5fa',
    severity: 'cloudy',
  },
  3: {
    code: 3,
    label: 'Overcast',
    description: 'Gray, cloud-covered sky with soft muted lighting',
    iconDay: 'Cloud',
    iconNight: 'Cloud',
    gradientClass: 'from-slate-500/10 via-gray-600/10 to-zinc-700/10 border-slate-400/20',
    accentColor: '#94a3b8',
    severity: 'cloudy',
  },
  45: {
    code: 45,
    label: 'Foggy',
    description: 'Reduced visibility due to atmospheric fog',
    iconDay: 'CloudFog',
    iconNight: 'CloudFog',
    gradientClass: 'from-slate-400/15 via-zinc-500/15 to-neutral-600/15 border-slate-300/30',
    accentColor: '#cbd5e1',
    severity: 'fog',
  },
  48: {
    code: 48,
    label: 'Depositing Rime Fog',
    description: 'Freezing fog forming ice crystal deposits on trees and ground',
    iconDay: 'CloudFog',
    iconNight: 'CloudFog',
    gradientClass: 'from-teal-500/10 via-slate-500/10 to-cyan-600/10 border-teal-300/20',
    accentColor: '#2dd4bf',
    severity: 'fog',
  },
  51: {
    code: 51,
    label: 'Light Drizzle',
    description: 'Fine, light mist-like precipitation',
    iconDay: 'CloudDrizzle',
    iconNight: 'CloudDrizzle',
    gradientClass: 'from-sky-500/10 via-blue-600/10 to-slate-700/10 border-sky-400/20',
    accentColor: '#38bdf8',
    severity: 'rain',
  },
  53: {
    code: 53,
    label: 'Moderate Drizzle',
    description: 'Steady fine rainfall with overcast condition',
    iconDay: 'CloudDrizzle',
    iconNight: 'CloudDrizzle',
    gradientClass: 'from-blue-500/15 via-indigo-600/15 to-slate-700/15 border-blue-400/20',
    accentColor: '#60a5fa',
    severity: 'rain',
  },
  55: {
    code: 55,
    label: 'Dense Drizzle',
    description: 'Heavy damp mist and dense drizzle',
    iconDay: 'CloudDrizzle',
    iconNight: 'CloudDrizzle',
    gradientClass: 'from-blue-600/15 via-sky-700/15 to-zinc-800/15 border-blue-500/25',
    accentColor: '#2563eb',
    severity: 'rain',
  },
  56: {
    code: 56,
    label: 'Light Freezing Drizzle',
    description: 'Supercooled drizzle freezing upon contact with surfaces',
    iconDay: 'CloudHail',
    iconNight: 'CloudHail',
    gradientClass: 'from-cyan-500/15 via-blue-600/15 to-slate-800/15 border-cyan-400/25',
    accentColor: '#22d3ee',
    severity: 'rain',
  },
  57: {
    code: 57,
    label: 'Dense Freezing Drizzle',
    description: 'Heavy freezing drizzle creating slippery ice patches',
    iconDay: 'CloudHail',
    iconNight: 'CloudHail',
    gradientClass: 'from-cyan-600/15 via-teal-700/15 to-slate-800/15 border-cyan-500/30',
    accentColor: '#06b6d4',
    severity: 'rain',
  },
  61: {
    code: 61,
    label: 'Slight Rain',
    description: 'Light continuous rain drops',
    iconDay: 'CloudRain',
    iconNight: 'CloudRain',
    gradientClass: 'from-blue-500/15 via-sky-600/15 to-slate-700/15 border-blue-400/20',
    accentColor: '#3b82f6',
    severity: 'rain',
  },
  63: {
    code: 63,
    label: 'Moderate Rain',
    description: 'Steady, moderate rainfall across the region',
    iconDay: 'CloudRain',
    iconNight: 'CloudRain',
    gradientClass: 'from-blue-600/20 via-indigo-700/20 to-slate-800/20 border-blue-500/30',
    accentColor: '#2563eb',
    severity: 'rain',
  },
  65: {
    code: 65,
    label: 'Heavy Rain',
    description: 'Torrential rain with high surface water accumulation',
    iconDay: 'CloudRainWind',
    iconNight: 'CloudRainWind',
    gradientClass: 'from-blue-700/20 via-indigo-800/20 to-zinc-900/20 border-blue-600/35',
    accentColor: '#1d4ed8',
    severity: 'rain',
  },
  66: {
    code: 66,
    label: 'Light Freezing Rain',
    description: 'Freezing rain forming glaze on roads and vegetation',
    iconDay: 'CloudHail',
    iconNight: 'CloudHail',
    gradientClass: 'from-sky-500/20 via-indigo-600/20 to-slate-800/20 border-sky-400/30',
    accentColor: '#38bdf8',
    severity: 'rain',
  },
  67: {
    code: 67,
    label: 'Heavy Freezing Rain',
    description: 'Severe freezing rain causing significant ice buildup',
    iconDay: 'CloudHail',
    iconNight: 'CloudHail',
    gradientClass: 'from-sky-600/20 via-blue-800/20 to-zinc-900/20 border-cyan-400/35',
    accentColor: '#0284c7',
    severity: 'rain',
  },
  71: {
    code: 71,
    label: 'Slight Snow Fall',
    description: 'Light flurries gently falling',
    iconDay: 'CloudSnow',
    iconNight: 'CloudSnow',
    gradientClass: 'from-indigo-400/15 via-sky-300/15 to-slate-600/15 border-indigo-300/25',
    accentColor: '#818cf8',
    severity: 'snow',
  },
  73: {
    code: 73,
    label: 'Moderate Snow Fall',
    description: 'Steady snowfall dusting roads and landscape',
    iconDay: 'CloudSnow',
    iconNight: 'CloudSnow',
    gradientClass: 'from-indigo-500/20 via-blue-400/20 to-slate-700/20 border-indigo-400/30',
    accentColor: '#6366f1',
    severity: 'snow',
  },
  75: {
    code: 75,
    label: 'Heavy Snow Fall',
    description: 'Dense snowfall with rapid snow depth accumulation',
    iconDay: 'Snowflake',
    iconNight: 'Snowflake',
    gradientClass: 'from-indigo-600/20 via-sky-500/20 to-slate-800/20 border-indigo-400/35',
    accentColor: '#4f46e5',
    severity: 'snow',
  },
  77: {
    code: 77,
    label: 'Snow Grains',
    description: 'Small, flat opaque ice grains drifting',
    iconDay: 'CloudSnow',
    iconNight: 'CloudSnow',
    gradientClass: 'from-sky-400/15 via-slate-500/15 to-zinc-700/15 border-sky-300/20',
    accentColor: '#a5f3fc',
    severity: 'snow',
  },
  80: {
    code: 80,
    label: 'Slight Rain Showers',
    description: 'Passing light showers with occasional clear breaks',
    iconDay: 'CloudSunRain',
    iconNight: 'CloudMoonRain',
    gradientClass: 'from-blue-500/15 via-sky-500/15 to-slate-700/15 border-blue-400/20',
    accentColor: '#38bdf8',
    severity: 'rain',
  },
  81: {
    code: 81,
    label: 'Moderate Rain Showers',
    description: 'Frequent showers with moderate intensity',
    iconDay: 'CloudSunRain',
    iconNight: 'CloudMoonRain',
    gradientClass: 'from-blue-600/20 via-sky-600/20 to-slate-800/20 border-blue-500/25',
    accentColor: '#2563eb',
    severity: 'rain',
  },
  82: {
    code: 82,
    label: 'Violent Rain Showers',
    description: 'Sudden intense downpours with gusty winds',
    iconDay: 'CloudRainWind',
    iconNight: 'CloudRainWind',
    gradientClass: 'from-blue-700/25 via-indigo-900/25 to-zinc-950/25 border-blue-500/35',
    accentColor: '#1e40af',
    severity: 'rain',
  },
  85: {
    code: 85,
    label: 'Slight Snow Showers',
    description: 'Brief localized snow bursts',
    iconDay: 'CloudSnow',
    iconNight: 'CloudSnow',
    gradientClass: 'from-indigo-400/15 via-slate-500/15 to-zinc-700/15 border-indigo-300/20',
    accentColor: '#a5b4fc',
    severity: 'snow',
  },
  86: {
    code: 86,
    label: 'Heavy Snow Showers',
    description: 'Heavy snow squalls with sudden drop in visibility',
    iconDay: 'Snowflake',
    iconNight: 'Snowflake',
    gradientClass: 'from-indigo-600/20 via-slate-600/20 to-zinc-800/20 border-indigo-400/30',
    accentColor: '#6366f1',
    severity: 'snow',
  },
  95: {
    code: 95,
    label: 'Thunderstorm',
    description: 'Thunder and lightning with rain showers',
    iconDay: 'CloudLightning',
    iconNight: 'CloudLightning',
    gradientClass: 'from-amber-600/20 via-purple-700/20 to-slate-900/20 border-amber-500/30',
    accentColor: '#f59e0b',
    severity: 'storm',
  },
  96: {
    code: 96,
    label: 'Thunderstorm with Hail',
    description: 'Severe thunderstorm accompanied by light hail stones',
    iconDay: 'CloudLightning',
    iconNight: 'CloudLightning',
    gradientClass: 'from-purple-600/25 via-amber-600/25 to-zinc-900/25 border-purple-500/35',
    accentColor: '#a855f7',
    severity: 'storm',
  },
  99: {
    code: 99,
    label: 'Heavy Thunderstorm with Hail',
    description: 'Dangerous severe storm with heavy hail and damaging winds',
    iconDay: 'CloudLightning',
    iconNight: 'CloudLightning',
    gradientClass: 'from-red-600/25 via-purple-800/25 to-black/30 border-red-500/40',
    accentColor: '#ef4444',
    severity: 'storm',
  },
};

export function getWMOInterpretation(code: number, isDay = 1): WMOInterpretation {
  const interp = WMO_Interpretation_Map[code] || WMO_Interpretation_Map[0];
  return {
    ...interp,
    iconDay: isDay ? interp.iconDay : interp.iconNight,
  };
}
